spring:
  profiles:
    active: ToMongo
    #active value change between 'FromNginx' and 'ToMongo'
server:
  port: 9000
  servlet:
    context-path: /CNPushToMQ
logging:
  config: classpath:log4j2.xml